default: playChateauDaimyo.cpp ChateauDaimyo.hpp ChateauDaimyo.cpp Space.hpp Space.cpp RicePaddy.hpp RicePaddy.cpp Wall.hpp Wall.cpp ChateauGround.hpp ChateauGround.cpp DaimyoRoom.hpp DaimyoRoom.cpp Player.hpp Player.cpp joeUtilities.hpp joeUtilities.cpp menu.hpp menu.cpp validateInputInclusive.hpp validateInputInclusive.cpp inputValidation.hpp inputValidation.cpp
	g++ -std=c++11 -ggdb playChateauDaimyo.cpp ChateauDaimyo.cpp Space.cpp RicePaddy.cpp Wall.cpp ChateauGround.cpp DaimyoRoom.cpp Player.cpp joeUtilities.cpp menu.cpp validateInputInclusive.cpp inputValidation.cpp -o playChateauDaimyo

clean:
	rm playChateauDaimyo
