default: tourInOut

tourInOut: Map.hpp Map.cpp tourInOut.cpp inputValidation.hpp inputValidation.cpp
	g++ -std=c++11 -ggdb Map.cpp tourInOut.cpp inputValidation.cpp -o tourInOut

clean:
	rm tourInOut
